sudo: required
language: python
python:
    - 3.6
before_install:
    - sudo pip install --upgrade pip
install:
    - pip install --only-binary=numpy,scipy numpy scipy
    - pip install -r requirements.txt
    - pip install coveralls
script: pytest --cov=planet test
after_success:
    - coveralls
notifications:
    - email: false
